name: easy_asset_generator
description: A Flutter asset code generator that creates structured Dart accessors for asset folders.
version: 0.0.1
homepage: https://github.com/ravindravala/easy_asset_generator
repository: https://github.com/ravindravala/easy_asset_generator
issue_tracker: https://github.com/ravindravala/easy_asset_generator/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2

executables:
  easy_asset_generator: easy_asset_generator
