// Auto-generated by EASY ASSET GENERATOR
// Do NOT modify this file manually!
// Generated on: 2025-07-05T21:01:03.114005

import 'images.dart';

/// Unified assets class providing type-safe access to all asset categories
/// Generated by Easy Asset Generator
/// 
/// Usage: Assets.images.imgLogo, Assets.fonts.fontRoboto
class Assets {
  const Assets._();

  static const Assets instance = Assets._();

  static Images get images => Images.instance;
}
