// Auto-generated by EASY ASSETS GENERATOR
// Do NOT modify this file manually!
// This file provides easy access to all asset categories.

import 'images.dart';

class Assets {
  const Assets._();

  static const Assets instance = Assets._();

  static Images get images => Images.instance;
}
