// Auto-generated by EASY ASSET GENERATOR
// Do NOT modify this file manually!
// Generated on: 2025-07-05T21:01:03.110510

class Images {
  const Images._();

  static const Images instance = Images._();

  // PNG assets
  static const String imgFaviconCopy = 'assets/images/favicon copy.png';
  static const String imgFavicon = 'assets/images/favicon.png';

}
