// Auto-generated by EASY ASSETS GENERATOR
// Do NOT modify this file manually!
// This file provides easy access to all asset categories.

class Images {
  const Images._();

  static const Images instance = Images._();

  static const String faviconCopy = 'assets/images/favicon copy.png';
  static const String favicon = 'assets/images/favicon.png';
}
