// Auto-generated by EASY ASSET GENERATOR
// Do NOT modify this file manually!
// Generated on: 2025-07-16T15:15:15.157343

class Images {
  const Images._();

  static const Images instance = Images._();

  // PNG assets
  static const String imgFlutterBrandlogo = 'assets/images/flutter-brandlogo.net_.png';

}
